apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: service_survey_postgres:5432
    database: service_survey_db
    user: admin
    secureJsonData:
      password: admin
    isDefault: true
    jsonData:
      sslmode: disable
