# Step 1: 베이스 이미지 설정 (Python 3.11)
FROM python:3.11.9

# Step 2: 작업 디렉토리 설정
WORKDIR /app

# Step 3: 필요한 패키지 설치
COPY requirements-web.txt .
RUN pip install --no-cache-dir -r requirements-web.txt

# Step 4: 소스 코드 복사
COPY . /app

# Step 5: Streamlit 앱 실행
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=18501", "--server.address=0.0.0.0"]
