# Github Repository에 code가 push되면 Github Action을 실행한다. 
name: Matrix Model Training Workflow

on:
  push:
    branches:
      - master  # Trigger on push to the master branch

jobs:
  run_model_training:
    runs-on: self-hosted
    strategy:
      matrix:
        model_type: [efficientnet, resnet, tinyvgg, cnn]  # 4개
        optimizer_type: [sgd, adam]  # 2개
        learning_rate: [0.001, 0.01]  # 2개 (범위 축소)
        epochs: [10, 20, 30]  # 3개 (범위 축소)
        batch_size: [32, 64]  # 2개 (범위 축소)
    steps:
      - name: Print folder path
        run: echo "${{ github.event.client_payload.folder_path }}"

      - name: 모델 훈련 실행
        run: |
          cd /home/ubuntu/coc-model
          /home/ubuntu/.pyenv/versions/modelenv-2/bin/python main.py Train \
            --dataset_version "version_1" \
            --model_type "${{ matrix.model_type }}" \
            --optimizer_type "${{ matrix.optimizer_type }}" \
            --epochs "${{ matrix.epochs }}" \
            --learning_rate "${{ matrix.learning_rate }}" \
            --batch_size "${{ matrix.batch_size }}"
