name: 이슈 닫힘 알림

on:
  issues:
    types: [ closed ]
  
jobs:
  issue-closed:
    runs-on: ubuntu-latest
    steps:
      - name: 이슈 닫힘 메시지 출력
        run: |
          echo "이슈가 닫혔습니다. 이슈 번호: ${{ github.event.issue.number }}"
          echo "이슈 제목: ${{ github.event.issue.title }}"
          echo "이슈 내용: ${{ github.event.issue.body }}"
