name: new model push to training

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  train-model:
    runs-on: [self-hosted, linux, X64]
    strategy:
      matrix:
        model_type: [cnn, resnet, efficientnet, tinyvgg]
        epoch: [10, 20]
        optimizer_type: ['adam', 'sgd']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: 디버그 로그 보기
        run: |
          echo "GITHUB_ACTIONS_DEBUG=true" >> $GITHUB_ENV

      - name: git pull
        run: |
          cd /home/ubuntu/flatfix
          git pull
          
      - name: python 설치
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.9

      - name: 의존성 설치
        run: |
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          pyenv activate modelenv-2
          pip install pytest
          pytest /home/ubuntu/flatfix/test/

        
      - name: 학습 실행
        run: |
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          pyenv activate modelenv-2
          python main.py Train --mlflow_uri http://13.124.132.135:15000 \
                               --backend_uri postgresql://master_user:proj777!@pgpool:5432/MLFLOW_DB \
                               --default-artifact-root s3://deprojteam07-datalake/model_registry
                               --model_type ${{ matrix.model-type }} \
                               --epochs ${{ matrix.epochs }} \
                               --optimizer_type ${{ matrix.optimizer_type }}

