name: new model push to training

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  train-model:
    runs-on: [self-hosted, linux, X64]
    strategy:
      matrix:
        model_type: ['cnn', 'resnet', 'efficientnet', 'tinyvgg']
        epoch: [10, 20]
        dataset_version: ['version_1']
        optimizer_type: ['adam', 'sgd']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: 디버그 로그 보기
        run: |
          echo "GITHUB_ACTIONS_DEBUG=true" >> $GITHUB_ENV

      - name: git pull
        run: |
          cd /home/ubuntu/flatfix
          git pull
          
      - name: python 설치
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.9

      - name: 의존성 설치
        run: |
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          pyenv activate modelenv-2
          pip install pytest
          pytest /home/ubuntu/flatfix/test/

      - name: 도커 컴포즈 업
        run: |
          cd /home/ubuntu/flatfix
          docker compose up --build -d

      - name: 학습 도커 이미지 빌드
        run: |
          cd /home/ubuntu/flatfix
          docker build -f Dockerfile.experiments -t train-model .

      - name: 학습
        run: |
          docker run train-model \
            --model_type ${{ matrix.model_type }} \
            --dataset_version ${{ matrix.dataset_version }} \
            --epoch ${{ matrix.epoch }} \
            --optimizer_type ${{ matrix.optimizer_type }}
