name: model training with docker compose

on:
  push:
  workflow_dispatch:

jobs: 
  train-model:
    runs-on: [self-hosted, linux, X64]
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 도커 컴포즈 업
        run: |
          cd /home/ubuntu/flatfix/app
          docker compose up
