name: new source push to training

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  train-model:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: 디버그 로그 보기
        run: |
          echo "GITHUB_ACTIONS_DEBUG=true" >> $GITHUB_ENV

      - name: git pull
        run: |
          cd /home/ubuntu/flatfix
          git pull
          
      - name: python 설치
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.9

      - name: 의존성 설치
        run: |
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          pyenv activate modelenv-2
          pip install pytest
          pytest /home/ubuntu/flatfix/test/

      - name: 도커 컴포즈 업
        run: |
          cd /home/ubuntu/flatfix
          docker compose up --build -d
          docker network ls
          docker inspect mlflow-server | grep "Networks"

      - name: 학습 resnet
        run: |
          docker run --network flatfix_mlflow-network --memory='4g' --rm train-model \
            python /app/main.py Train \
            --model_type resnet \
            --dataset_version version_1 \
            --epochs 5 \
            --optimizer_type adam
          docker inspect train-model | grep "Networks"

      - name: 학습 efficientnet
        run: |
          docker run --network flatfix_mlflow-network --rm train-model \
            python /app/main.py Train \
            --model_type efficientnet \
            --dataset_version version_1 \
            --epochs 5 \
            --optimizer_type adam
          docker inspect train-model | grep "Networks"


      - name: 학습 tinyvgg
        run: |
          docker run --network flatfix_mlflow-network --rm train-model \
            python /app/main.py Train \
            --model_type tinyvgg \
            --dataset_version version_1 \
            --epochs 5 \
            --optimizer_type adam
          docker inspect train-model | grep "Networks"


