name: CI/CD 

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: self-hosted
    steps:
       # mlflow 서버는 서우님이 사용하고 계시기 떄문에 작업을 할 수 없다. 
       # 나만의 mlflow 서버를 만들어야 하나 고민중이다...
       - name: Check if MLflow server is running with absolute path 
         run: |
           echo "MLflow 서버 상태를 확인하는 작업은 보류입니다."

      
       # Flask 서버가 켜져 있으면 끄는 작업을 한다. 
       - name: Check if Flask server is running with absolute path
         run: |
          if pgrep -f "/home/ubuntu/youngwoo-flask-app/backend_app_v1.py"; then
            echo "Flask 서버가 켜져있습니다."
            echo "Automated Pipeline를 실행해야 되서 재정비를 해야 하므로 Flask 서버를 종료하겠습니다."
            pkill -f "/home/ubuntu/youngwoo-flask-app/backend_app_v1.py"
            echo "Flask 서버를 종료했습니다."
          else
            echo "Flask 서버가 이미 꺼져 있는 상태이므로 별다른 작업을 하지 않겠습니다."
          fi


       # Streamlit 서버가 켜져 있으면 끄는 작업을 한다.
       - name: Check if Streamlit server is running
         run: |
           if pgrep -f "/home/ubuntu/youngwoo-flask-app/fronted_app_v1.py"; then
             echo "Streamlit 서버가 켜져있습니다."
             echo "Automated Pipeline을 실행해야 되서 재정비를 해야 하므로 Streamlit 서버를 종료하겠습니다."
             pkill -f "/home/ubuntu/youngwoo-flask-app/fronted_app_v1.py"
             echo "Streamlit 서버를 종료했습니다."
           else
             echo "Streamlit 서버가 이미 종료된 상태이므로 별다른 작업을 하지 않겠습니다."
           fi
       


       # mlflow 서버를 켜는 작업을 한다. 



       # 모델 코드의 시작점인 main.py를 실행해서 Automated Piepline에 이어서 모델 관련 지표, 모델 등록과 관련된 작업을 할 수 있도록 한다. 

       


       # Flask 서버를 켠다. 
       



       # Streamlit 서버를 켠다. 


       
      
